# variable prompting 
- name: variable prompting
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter user name 
    private: false
  - name: PASSWORD
    prompt: Please enter password
    private: false
  tasks: 
  - name : Print and check the values
    ansible.builtin.debug:
      msg: " the user name is: {{USERNAME}} and password is: {{PASSWORD}}"