- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print packages
    ansible.builtin.package:
      msg: " {{item}}"
      state: present
    loop:
    - git
    - postfix
    - mysql 